language: cpp
os: linux
dist: focal
arch: arm64-graviton2
addons:
  apt:
    packages:
      - scilab
      - octave
      - build-essential
      - liboctave-dev
      - octave-signal
      - octave-struct
      - octave-communications
      - octave-strings

script:
- cd $TRAVIS_BUILD_DIR/
- cd src/
- bash make.sh
- cd $TRAVIS_BUILD_DIR/
- scilab-cli -f tests/test.sce 
